application/models.py
from flask import abort

from application import db

class CRUDMixin(object):
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True)

    @classmethod
    def get_by_id(cls, id):
        if any(
            (isinstance(id, basestring) and id.isdigit(),
             isinstance(id, (int, float))),
        ):
            response = cls.query.get(int(id))
            if not response:
                abort(404)
            return response
        abort(404)

    @classmethod
    def get_by_name(cls, name):
        return cls.query.filter_by(name=name).first_or_404()

    @classmethod
    def create(cls, **kwargs):
        instance = cls(**kwargs)
        return instance.save()

    def update(self, commit=True, **kwargs):
        for attr, value in kwargs.iteritems():
            setattr(self, attr, value)
        return commit and self.save() or self

    def save(self, commit=True):
        db.session.add(self)
        if commit:
            db.session.commit()
        return self

    def delete(self, commit=True):
        db.session.delete(self)
        return commit and db.session.commit()

application/branches/forms.py
from wtforms import Form, StringField, validators

from application.utils import create_identifier, create_message

from flask_babel import gettext as _

class CommitForm(Form):
    message = create_message(_('Message'))

class BranchForm(Form):
    name = create_identifier(_('Branch name'))

application/projects/forms.py
from wtforms import Form
from application.utils import create_identifier

from flask_babel import gettext as _


class ProjectForm(Form):
    name = create_identifier(_('Project name'))

class FileForm(Form):
    name = create_identifier(_('File name'))

application/users/forms.py
from flask_babel import gettext as _
from wtforms import Form, SelectMultipleField

class SubscriptionForm(Form):
    subscriptions = SelectMultipleField('Subscriptions', choices=[])

application/branches/__init__.py
from model import *
from forms import *
from tasks import *

application/projects/__init__.py
from model import *
from forms import *

application/tasks/__init__.py
from projects import *

application/users/__init__.py
from model import *
from forms import *

application/views/projects.py
import os
import git
from os.path import join, isdir, isfile, splitext
from functools import wraps
import json

import flask
from flask import (
    g, Blueprint, request, render_template,
    url_for, flash, redirect, send_from_directory, abort
)
from flask_user import login_required, current_user
from flask_babel import gettext as _
from sqlalchemy import desc
from werkzeug import secure_filename, FileStorage
from PIL import Image
from shutil import copyfile

from application import db, app, limiter
from application.projects import (
    Project, ProjectForm, FileForm
)
from application.branches import (
    Branch, get_sub_branches,
    get_merge_pendencies, build_branch
)
import application.views
from application.utils import (
    write_file, extension, lowercase_ext, resolve_conflict
)

IMAGES = tuple('jpg jpe jpeg png gif svg bmp'.split())

class UploadNotAllowed(Exception):
    """
    This exception is raised if the upload was not allowed. You should catch
    it in your view code and display an appropriate message to the user.
    """

projects = Blueprint('projects', __name__, url_prefix='/<project>')

def require_projct_owner(func):
    """
    A view decorator that restricts access to owner of project
    """
    @wraps(func)
    def decorated_function(*args, **kwargs):
        if current_user != g.project.owner:
            flash(_('You are not the owner of this project'), 'error')
            return redirect(url_for('branches.view', project=g.project.name,
                                    branch='master', filename='index.html'))
        return func(*args, **kwargs)
    return decorated_function

@projects.url_value_preprocessor
def projects_url_value_preprocessor(endpoint, values):
    g.project = Project.get_by_name(values.get('project'))
    values['project'] = g.project

@projects.before_request
def projects_before_request():
    application.views.bookcloud_before_request()
    g.menu['left'].append({
            'name': _('Discussion'),
            'url': url_for('threads.query_thread', project=g.project.name),
            'external': True})
    g.menu['left'].append({
        'name': g.project.name,
        'sub_menu': [{
            'name': _('Visit master'),
            'url': url_for('branches.view', project=g.project.name,
                           branch='master', filename='index.html')
        }, {
            'name': _('Branches'),
            'url': url_for('projects.branches', project=g.project.name)
        }, {
            'name': _('Manage'),
            'url': url_for('projects.dashboard', project=g.project.name)
        }, {
            'name': _('View pdf'),
            'url': url_for('branches.pdf', project=g.project.name,
                           branch='master'),
            'external': True
        }, {
            'name': _('Upload Figure'),
            'url': url_for('projects.upload_resource', project=g.project.name),
            'external': True}]})

@projects.context_processor
def project_context_processor():
    return { 'project': g.project,
             'menu': g.menu }

@projects.route('/branches', methods = ['GET', 'POST'])
@limiter.exempt
def branches(project):
    return render_template('branches.html')

# Wrap in job queue
@projects.route('/dashboard', methods = ['GET', 'POST'])
@limiter.exempt
def dashboard(project):
    tree = [ get_sub_branches(project.get_master()) ]
    log = project.get_master().get_log()
    master_path = project.get_master().get_source_path()
    files = project.get_files()
    files.sort()
    files = [(splitext(f)[0], splitext(f)[1],
              int(os.stat(join(master_path, f)).st_size / 500)) for f in files]
    return render_template('dashboard.html', tree=tree, log=log, files=files)

# Wrap in job queue
@projects.route('/newfile', methods = ['GET', 'POST'])
@login_required
@require_projct_owner
def newfile(project):
    form = FileForm(request.form)
    # will be deprecated
    merge_pendencies = get_merge_pendencies(project.name, 'master')
    if merge_pendencies:
        return merge_pendencies
    ####################
    if request.method == 'POST' and form.validate():
        try:
            project.new_file(form.name.data)
        except application.projects.FileExists:
            flash(_('This file name name already exists'), 'error')
            return render_template('newfile.html', form=form)
        flash(_('File created successfuly!'), 'info')
        task = build_branch.delay(project.get_master().id)
        return render_template(
            'waiting.html', task_id=task.task_id,
            next_url=url_for('projects.dashboard', project=project.name))
    return render_template('newfile.html', form=form)

# Wrap in job queue
@projects.route('/renamefile/<oldfilename>', methods = ['GET', 'POST'])
@login_required
@require_projct_owner
def renamefile(project, oldfilename):
    form = FileForm(request.form)
    # will be deprecated
    merge_pendencies = get_merge_pendencies(project.name, 'master')
    if merge_pendencies:
        return merge_pendencies
    ####################
    if request.method == 'POST' and form.validate():
        try:
            project.rename_file(oldfilename, form.name.data)
            flash(_('File renamed successfuly!'), 'info')
            task = build_branch.delay(project.get_master().id)
            return render_template(
                'waiting.html', task_id=task.task_id,
                next_url=url_for('branches.view',
                                 project=project.name,
                                 branch='master', filename=form.name.data))
        except application.projects.FileExists:
            flash(_('This file name already exists'), 'error')
        except application.projects.FileNotFound:
            flash(_('File not found'), 'error')
    return render_template('renamefile.html', old_name=oldfilename, form=form)

@projects.route('/deletefile/<filename>')
@login_required
@require_projct_owner
def deletefile(project, filename):
    # will be deprecated
    merge_pendencies = get_merge_pendencies(project.name, 'master')
    if merge_pendencies:
        return merge_pendencies
    ####################
    try:
        project.delete_file(filename)
        flash(_('File removed successfuly!'), 'info')
        task = build_branch.delay(project.get_master().id)
        return render_template(
            'waiting.html', task_id=task.task_id,
            next_url=url_for('branches.view', project=project.name,
                             branch='master', filename='index'))
    except application.projects.FileNotFound:
        flash(_('File not found'), 'error')
    except application.projects.FileNotEmpty:
        flash(_('This file is not empty'), 'error')
    return redirect(url_for('projects.dashboard', project=project.name))

# API routes
@projects.route('/upload_resource', methods = ['GET', 'POST'])
@login_required
def upload_resource(project):
    if request.method == 'GET':
        return '''
        <!doctype html>
        <title>Upload new File</title>
        <h1>Upload new File</h1>
        <form method=post enctype=multipart/form-data>
        <p><input type=file name=file>
        <input type=submit value=Upload>
        </form>
        '''
    if 'file' not in request.files:
        return json.dumps({
            'message': _('No file'),
            'status': 'error'
        })
    file = request.files['file']
    if file.filename == '':
        return json.dumps({
            'message': _('No selected file'),
            'status': 'error'
        })
    basename = lowercase_ext(secure_filename(file.filename))
    if extension(basename) not in IMAGES:
        return json.dumps({
            'message': _('File format not allowed'),
            'status': 'error'
        })
    folder = join(project.get_folder(), '_resources')
    original_folder = join(folder, 'original')
    if os.path.exists(join(original_folder, basename)):
        basename = resolve_conflict(original_folder, basename)
    target = join(original_folder, basename)
    file.save(target)
    # save low_resolution
    # put this inside celery task
    if extension(basename) == 'gif':
        copyfile(target, join(folder, 'low_resolution', basename))
        name, ext = os.path.splitext(basename)
        image = Image.open(target)
        image.save(join(folder, 'low_resolution', name + '.png'))
    else:
        image = Image.open(target)
        basewidth = 500
        wpercent = (basewidth/float(image.size[0]))
        hsize = int((float(image.size[1])*float(wpercent)))
        image = image.resize((basewidth,hsize), Image.ANTIALIAS)
        image.save(join(folder, 'low_resolution', basename))
    # save thumbnail
    image = Image.open(target)
    basewidth = 40
    wpercent = (basewidth/float(image.size[0]))
    hsize = int((float(image.size[1])*float(wpercent)))
    image = image.resize((basewidth,hsize), Image.ANTIALIAS)
    image.save(join(folder, 'thumbnail', basename))
    # here there has to be some thumbnailing
    if extension(basename) == 'gif':
        name, ext = os.path.splitext(basename)
        return ".. figure:: _resources/" + name + ".*"
    return ".. figure:: _resources/" + basename
    app.logger.info('Uploading file {} from project {}'.format(
        file.filename, project.name))
    return json.dumps({
        'message': _('Image saved successfully'),
        'status': 'success',
        'filename': basename
    })

# should be served by web server
# need to have webserver add project path
@projects.route('/resources/<path:filename>')
@limiter.exempt
def resources(project, filename):
    return send_from_directory(
        os.path.abspath(join(project.get_folder(), '_resources/original')),
        filename)

# should be served by web server
# need to have webserver add project path
# need to see all the cases of path:anything
@projects.route('/<path:anything>/_resources/<path:filename>')
@limiter.exempt

application/views/tasks.py
import re

from application import app, limiter, ext
from flask import jsonify

from application.views import internal_server_error

from pygtail import Pygtail

from celery.result import AsyncResult

#from werkzeug.utils import secure_filename

@limiter.exempt
@app.route('/tasks/<path:task_id>')
def tasks(task_id):
    task_id = re.sub('/', '', task_id)
    task = AsyncResult(task_id)

    if (task.state == 'PENDING'):
        return jsonify({ 'state': task.state })

    if (task.state == 'PROGRESS'):
        return jsonify({ 'state': task.state,
                         'status': task.info.get('status', '') })

    if (task.state == 'FAILURE'):
        internal_server_error(task.result)
        return jsonify({ 'state': task.state,
                         'result': task.result.message,
                         'traceback': task.traceback })

    if (task.state == 'SUCCESS'):
        return jsonify({ 'state': task.state })

    return jsonify({ 'state': task.state })

application/views/users.py
from flask import (Blueprint, render_template, request,
                   redirect, url_for, g, flash)
from flask_user import login_required, current_user
from flask_babel import gettext as _

from application import db, app
from application.projects import Project
from application.branches import Branch
from application.threads import Named_Tag
from application import app, limiter
import application

from application.users import SubscriptionForm

users = Blueprint('users', __name__)

@users.route('/login')
def login():
    return redirect(url_for('user.login'))

@users.route('/logout')
def logout():
    return redirect(url_for('user.logout'))

@users.before_request
def projects_before_request():
    application.views.bookcloud_before_request()

@users.context_processor
def users_context_processor():
    return { 'menu': g.menu }

@users.route('/profile')
@limiter.exempt
@login_required
def profile():
    projects = list(Project.query.all())
    branches = list(Branch.query.filter(Branch.owner==current_user).all())
    return render_template('profile.html', projects=projects, branches=branches,
                           user=current_user,
                           properties=app.config['USER_PROPERTIES'])

@users.route('/update_profile', methods = ['GET', 'POST'])
@limiter.limit("10 per day")
@login_required
def update_profile():
    if request.method == 'POST':
        for item in app.config['USER_PROPERTIES']:
            if request.form.has_key(item['variable']):
                if item['type'] == 'boolean':
                    if request.form[item['variable']] == 'yes':
                        setattr(current_user, item['variable'], True)
                    else:
                        setattr(current_user, item['variable'], False)
                if item['type'] == 'integer':
                    setattr(current_user, item['variable'],
                            item['choices']
                            .index(request.form[item['variable']]))
        db.session.commit()
        app.logger.info('Updating profile of user {}'.format(
            current_user.username))
        flash(_('Profile updated'), 'info')
        return redirect(url_for('users.profile'))
    return render_template('update_profile.html', user=current_user,
                           profile_form=app.config['USER_PROPERTIES'])

@users.route('/subscriptions', methods = ['GET', 'POST'])
@limiter.limit("10 per day")
@login_required
def subscriptions():
    form = SubscriptionForm(request.form)
    form.subscriptions.choices = [(str(t.id), t.project.name + ' - ' + t.name)
                                  for t in Named_Tag.query.all()]
    if request.method == 'POST' and form.validate():
        if not form.subscriptions.data:
            form.subscriptions.data = []
        subscription_list = (Named_Tag
            .query.filter(Named_Tag.id.in_(form.subscriptions.data))).all()
        current_user.subscriptions = subscription_list
        db.session.commit()
        app.logger.info('Updating subscriptions of user {}'.format(
            current_user.username))
        flash(_('Subscriptions updated'), 'info')
        return redirect(url_for('users.profile'))
    form.subscriptions.default = [t.id for t in current_user.subscriptions]
    form.subscriptions.process(request.form)
    return render_template('subscriptions.html', form=form)

application/templates/_diff.html
{% macro file_diff_style() %}

<style>
/* Blob, Blame, Diff View */
.line { display: block; }
.linenos { background-color: #f9f9f9; text-align: right; }
.linenos a { color: #888; }
.linenos a:hover { text-decoration: none; }
.highlight-line, .highlight-line .line { background-color: #fefed0; }
.linenos a { padding: 0 6px 0 6px; }

/* Commit View taken from kaus, by Jonas Haag */
.full-commit { width: 100% !important; margin-top: 10px; }

.full-commit .commit { padding: 15px 20px; }
.full-commit .commit .line1 { padding-bottom: 5px; }
.full-commit .commit:hover .line1 { text-decoration: none; }
.full-commit .commit .line2 > span { float: left; }

.full-commit .summary { color: #737373; font-size: 80%; margin-top: 25px; }
.full-commit .summary .additions { color: #008800; }
.full-commit .summary .deletions { color: #ee4444; }

.full-commit .file.collapsed > table { display: none; }

.diff { font-family: monospace; }
.diff .filename {
  padding: 8px 10px;
  background-color: #f9f9f9;
  border: 1px solid #e0e0e0;
  margin-top: 25px;
}
.diff .filename del { color: #999; }
.diff .filename .summary { float: left; margin: -4px 15px 0 -5px; font-size: 80%; }
.diff .filename .summary .additions { color: green; }
.diff .filename .summary .deletions{ color: red; }

.diff .togglers { float: right; }
.diff .togglers a { opacity: 0.5; }
.diff .file:not(.collapsed) .togglers .expand   { display: none; }
.diff .file.collapsed       .togglers .collapse { display: none; }

.diff table, .diff .emptydiff {
  border: 1px solid #e0e0e0;
  border-top: 0;
  background-color: #fdfdfd;
  display: block;
}
.diff .emptydiff {
  padding: 7px 10px;
}
.diff td {
  padding: 0;
  border-left: 1px solid #e0e0e0;
}
.diff td .line { padding: 1px 10px; display: block; min-height: 1.2em; white-space: pre-wrap; }
.diff .linenos { font-size: 85%; padding: 0; vertical-align: top; }
.diff .linenos a { display: block; padding-top: 1px; padding-bottom: 1px; }
.diff td + td + td { width: 100%; }
.diff tr:first-of-type td { padding-top: 7px; }
.diff tr:last-of-type td { padding-bottom: 7px; }
.diff table .del { background-color: #ffdddd; }
.diff table .add { background-color: #ddffdd; }
.diff table .no-newline-marker { font-size: 50%; margin-left: 5px; color: red; }
.diff table del { background-color: #ee9999; text-decoration: none; }
.diff table ins { background-color: #99ee99; text-decoration: none; }
.diff .sep > td {
  height: 1.2em;
  text-align: center;
  background-color: #f9f9f9;
  border: 1px solid #e0e0e0;
}
.diff .sep:hover > td { background-color: #f9f9f9; }

</style>

{% endmacro %}

{% macro display_file_diff(repo, old_commit, new_commit) %}

  {% set summary, file_changes = commit_diff(repo, old_commit, new_commit) %}
  <div class=full-commit>
    {# Try to put this data as well, but there will be various commits
    <div class=commit>
      <span class=line1>
        <span>{{ commit.message|force_unicode }}</span>
      </span>
      <span class="line2 separated-by-dots">
        {% if commit.author != commit.committer %}
          <span>{{ commit.author|force_unicode|extract_author_name }} authored <span class=hastooltip title="{{ commit.author_time|formattimestamp  }}" uk-tooltip>{{ commit.author_time|timesince }}</span></span>
          <span>{{ commit.committer|force_unicode|extract_author_name }} committed <span class=hastooltip title="{{ commit.commit_time|formattimestamp  }}" uk-tooltip>{{ commit.commit_time|timesince }}</span></span>
        {% else %}
          <span>{{ commit.committer|force_unicode|extract_author_name }}</span>
          <span class=hastooltip title="{{ commit.commit_time|formattimestamp  }}" uk-tooltip>{{ commit.commit_time|timesince }}</span>
        {% endif %}
      </span>
      <span class=clearfloat></span>
    </div>
    #}

    <div class="summary separated-by-dots">
      <span>
        {{ summary.nfiles }} changed file(s)
        with <span class=additions>{{ summary.nadditions }} addition(s)</span>
        and <span class=deletions>{{ summary.ndeletions }} deletion(s)</span>.
      </span>
      {# I don't see use for raw diff here
      <span>
        <a href="{{ url_for('patch', repo=repo.name, rev=commit.id) }}">
          Raw diff
        </a>
      </span>
      #}
      <span>
        <a href=# onclick="toggler.collapseAll('.file'); return false">
          Collapse all
        </a>
      </span>
      <span>
        <a href=# onclick="toggler.expandAll('.file'); return false">
          Expand all
        </a>
      </span>
    </div>

    <div class=diff style="font-size: 80% !important;">
    {% for file in file_changes %}
      <div class=file>
        {% set fileno = loop.index0 %}

        <div class=filename>
          {% if not file.get('is_binary') %}
          <div class="summary hastooltip"
               title="{{ file.additions }} addition(s), {{ file.deletions }} deletion(s)" uk-tooltip>
            <div class=additions>+{{ file.additions }}</div>
            <div class=deletions>-{{ file.deletions }}</div>
          </div>
          {% endif %}
          {# TODO dulwich doesn't do rename recognition
          {% if file.old_filename != file.new_filename %}
            {{ file.old_filename }} →
          {% endif %}#}
            {% if file.new_filename == '/dev/null' %}
              <del>{{ file.old_filename|force_unicode }}</del>
            {% else %}
              {# <a href="/??? {{ url_for('blob', repo=repo.name, rev=rev, path=file.new_filename) }} "> #}
                {{ file.new_filename|force_unicode }}
              {# </a> #}
            {% endif %}

            <span class=togglers>
              <a onclick="toggler.collapse(this.parentNode.parentNode.parentNode); return false"
                 class=collapse href=#>less</a>
              <a onclick="toggler.expand(this.parentNode.parentNode.parentNode); return false"
                 class=expand href=#>more</a>
            </span>
        </div>

        {% if file.get('is_binary') %}
          <div class=emptydiff>Binary diff not shown</div>
        {% else %}
          <table>
            {% for chunk in file.chunks %}

              {%- for line in chunk -%}
                <tr>

                  {#- left column: linenos -#}
                  {%- if line.old_lineno is not none -%}
                    <td class=linenos><a href="#{{fileno}}-L-{{line.old_lineno}}">{{ line.old_lineno }}</a></td>
                    {%- if line.new_lineno is not none -%}
                      <td class=linenos><a href="#{{fileno}}-L-{{line.old_lineno}}">{{ line.new_lineno }}</a></td>
                    {%- else -%}
                      <td class=linenos></td>
                    {%- endif -%}
                  {%- else %}
                    <td class=linenos></td>
                    <td class=linenos><a href="#{{fileno}}-R-{{line.new_lineno}}">{{ line.new_lineno }}</a></td>
                  {% endif %}

                  {#- right column: code -#}
                  {%- if line.old_lineno -%}
                    {%- set line_id = "%s-L-%s"|format(fileno, line.old_lineno) -%}
                  {%- else -%}
                    {%- set line_id = "%s-R-%s"|format(fileno, line.new_lineno) -%}
                  {%- endif -%}
                  <td class="{{ line.action }}">
                    <span id="{{ line_id }}">
                      {#- lineno anchors -#}
                      <a name="{{ line_id }}"></a>
                      {#- the actual line of code -#}
                      <span class=line>{% autoescape false %}{{ line.line|force_unicode }}{% endautoescape %}{% if line.no_newline %}<span class="hastooltip no-newline-marker" title="No newline at end of file" uk-tooltip>⏎</span>{% endif %}</span>
                    </span>
                  </td>

                </tr>
              {%- endfor -%} {# lines #}

              {% if not loop.last %}
                <tr class=sep>
                  <td colspan=3></td>
                </tr>
              {% endif %}

            {% else %}
              {% if file.old_filename == '/dev/null' %}
              <div class=emptydiff>(New empty file)</div>
              {% elif file.new_filename == '/dev/null' %}
              <div class=emptydiff>(Empty file)</div>
              {% else %}
              {# This case happens if a file has undergone only mode changes.
                 In the future, if we have rename recognition, it may also happen
                 if the file has been renamed without having its content changed.
                 Currently, renames are always reported by dulwich as a file
                 deletion and addition. #}
              <div class=emptydiff>(No changes)</div>
              {% endif %}
            {%- endfor -%} {# chunks #}
          </table>
        {% endif %}

        </div>
    {% endfor %}
    </div>

  </div>

  <script>
    highlight_linenos({linksSelector: '.linenos a'});
  </script>

{% endmacro %}

application/templates/branch.html
{% extends "base_template.html" %}

{% block title %}{{_('Project (%(project)s), branch (_%(branch)s)') | format(project=project.name, branch=branch.name) }}{% endblock%}

{% macro contents() %}
  <h1>
    {{ _('%(branch)s') | format(branch=branch.name) }}
  </h1>

  <a class="uk-button uk-button-primary"
     href="{{ url_for('branches.view',
                      project=project.name,
                      branch=branch.name, filename='index.html') }}">
    {{ _('Visit branch') }}
  </a>

  {% if current_user == project.owner %}
    <a class="uk-button uk-button-primary"
       href="{{ url_for('projects.newfile',
                        project=project.name,
                        branch=branch.name) }}">
      {{ _('Create a new file') }}
    </a>
  {% endif %}

  <h2>{{ _('Last commits in _%s:') % branch.name }}</h2>
    <div class="code highlight-default">
      <div class="highlight">
        <pre><span class="n" style="font-size:small">{{ log }}</span></pre>
      </div>
    </div>

{% endmacro %}

application/templates/clone.html
{% extends "base_template.html" %}

{% from "_formhelpers.html" import render_field %}

{% block title %}{{ _('Create your own branch of this project') }}{% endblock%}

{% macro contents() %}
  <div class="uk-margin-large-left uk-card uk-card-default uk-card-body">
    <form method="POST">
      <fieldset class="uk-fieldset">
        <legend class="uk-legend">{{ _('Create your own branch of this project') }}</legend>
        <div class="uk-margin">
          {{ render_field(form.name) }}
        </div>
        <div class="uk-margin">
          <button class="uk-button uk-button-primary">Submit</button>
        </div>
    </form>
  </div>
{% endmacro %}

application/templates/just_view.html
{{doc|safe}}

application/templates/profile.html
{% extends "base_template.html" %}

{% block title %}{{ user.username }} profile{% endblock%}

{% macro contents() %}
  <!-- Card -->
  <div class="uk-grid-small uk-child-width-1-4@s uk-flex-center uk-text-center" uk-grid>
    <div class="uk-card uk-card-default uk-width-1-2@m">
      <div class="uk-card-header uk-flex-center">
        <div class="uk-grid-small uk-flex-center" uk-grid>
          <div class="uk-width-auto">
            <canvas width="80" height="80" data-jdenticon-hash="{{ hash(current_user.username) }}"
                    style="vertical-align: baseline;"></canvas>
          </div>
        </div>
        <div class="uk-width-auto">
          <h3 class="uk-card-title uk-margin-remove-bottom">{{ user.username }}</h3>
          {{ current_user.email }}
        </div>
      </div>
      {% if current_user.confirmed_at %}
        <div class="uk-card-footer">
          {{ current_user.confirmed_at }}
        </div>
      {% endif %}
    </div>
  </div>

  <h2>{{ _('Subscriptions' )}}</h2>

  <ul class="uk-list">
    {% for s in current_user.subscriptions %}
    <li>
      <span class="uk-label uk-label-success">{{ s.project.name + ' - ' + s.name }}</span>
    </li>
    {% endfor %}
  </ul>
  <a href="{{ url_for('users.subscriptions') }}"
     class="uk-button uk-button-primary">{{ _('Manage') }}</a>

  <!-- Branches -->
  <h2>{{ _('Your branches') }}</h2>
  <table class="uk-table uk-table-striped">
    <thead>
      <tr>
        <th>{{ _('Project') }}</th>
        <th>{{ _('Branch owner') }}</th>
        <th>{{ _('Branch') }}</th>
        <th>{{ _('Father branch') }}</th>
      </tr>
    </thead>
    <tbody>
      {% for b in branches %}
        <tr>
          <td>
            <a href="{{ url_for('projects.dashboard', project=b.project.name) }}">
              {{ b.project.name }}
            </a>
          <td>{{ b.owner.username }}</td>
          <td>
            <a href="{{ url_for('branches.branch', project=b.project.name,
                                branch=b.name) }}">
              {{ b.name }}
            </a>
          </td>
          <td>
            <a href="{{ url_for('branches.branch', project=b.project.name,
                                branch=b.origin.name) }}">
              {{ b.origin.name }}
            </a>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <!-- Profile -->
  <h2>{{ _('Profile') }}</h2>
  <table class="uk-table uk-table-striped">
    <tbody>
      <tr>
        <td>{{ _('First Name') }}</td>
        <td>{{ current_user.first_name }}</td>
      </tr>
      <tr>
        <td>{{ _('Last Name') }}</td>
        <td>{{ current_user.last_name }}</td>
      </tr>
      {% for item in properties %}
        <tr>
          {% if item['type'] == 'boolean' %}
            <td> {{ item['title'] }} </td>
            <td>
              {% if getattr(user, item['variable']) is not none %}
                {{ getattr(user, item['variable']) }}
              {% else %}
                {{ _('Not answered') }}
              {% endif %}
            </td>
          {% endif %}
          {% if item['type'] == 'string' %}
            <td> {{ item['title'] }} </td>
            <td>
              {% if getattr(user, item['variable']) is not none %}
                {{ getattr(user, item['variable']) }}
              {% else %}
                {{ _('Not answered') }}
              {% endif %}
            </td>
          {% endif %}
          {% if item['type'] == 'integer' %}
            <td> {{ item['title'] }} </td>
            <td>
              {% if getattr(user, item['variable']) is not none %}
                {{ item['choices'][getattr(user, item['variable'])] }}
              {% else %}
                {{ _('Not answered') }}
              {% endif %}
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a class="uk-button uk-button-primary" href="{{ url_for ('users.update_profile') }}">update</a>

{% endmacro %}

application/templates/reviewer.html
{% extends "layout.html" %}

{% block title %}{{ text['title'] }}{% endblock%}

{% macro contents() %}
<h1>{{ text['headline'] }}</h1>
<ul id="navigation">
  {% for r in reviewers %}
  <li>
    <a href="/{{ project }}/clone/{{ r }}">{{ r }}</a>
  </li>
  {% endfor %}
</ul>

{% endmacro %}