application/branches/forms.py
from wtforms import Form, StringField, validators

from application.utils import create_identifier, create_message

from flask_babel import gettext as _

class CommitForm(Form):
    message = create_message(_('Message'))

class BranchForm(Form):
    name = create_identifier(_('Branch name'))

application/projects/forms.py
from wtforms import Form
from application.utils import create_identifier

from flask_babel import gettext as _


class ProjectForm(Form):
    name = create_identifier(_('Project name'))

class FileForm(Form):
    name = create_identifier(_('File name'))

application/__init__.py
import os
from os.path import join
from flask_user import current_user

from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import relationship
from flask_babel import Babel, gettext as _
from flask_user import login_required, UserManager, UserMixin, SQLAlchemyAdapter, current_user

# limit number of visits
from flask_limiter import Limiter
from flask_assets import Environment, Bundle

import utils

# Setup Flask app and app.config
app = Flask(__name__, instance_relative_config=True)

limiter = Limiter(
    app,
    key_func=utils.get_identifier,
    global_limits=["200 per day", "50 per hour"])

# Initialize Flask-SQLAlchemy
db = SQLAlchemy(app)

# Setup Flask-Mail
mail = Mail()

assets = Environment()

babel = Babel()

from users import User

def create_app(extra_config_settings={}):
    """
    Initialize Flask applicaton
    """

    # Setup Flask-Assets
    assets.init_app(app)
    # Configure app
    app.config.from_object('config')
    app.config.from_pyfile('instance_config.py')
    with app.app_context():
        assets.load_path = [
            join(os.path.dirname(__file__), 'static/vendor/bower_components/'),
            join(os.path.dirname(__file__), 'static/'),
            join(app.config['CONFIG_PATH'], 'theme', 'static')
        ]
    assets.register(
        'js_all',
        Bundle(
            'klaus.js',
            'jquery/dist/jquery.min.js',
            Bundle('uikit/dist/js/uikit.min.js',
                   'uikit/dist/js/uikit-icons.min.js'
               ),
            'Jdenticon/dist/jdenticon.min.js',
            Bundle('jquery-textext/src/js/textext.core.js',
                   'jquery-textext/src/js/textext.plugin.tags.js',
                   'jquery-textext/src/js/textext.plugin.autocomplete.js',
                   'jquery-textext/src/js/textext.plugin.suggestions.js',
                   'jquery-textext/src/js/textext.plugin.filter.js',
                   'jquery-textext/src/js/textext.plugin.clear.js',
                   'jquery-textext/src/js/textext.plugin.focus.js',
                   'jquery-textext/src/js/textext.plugin.prompt.js',
                   'jquery-textext/src/js/textext.plugin.ajax.js',
                   'jquery-textext/src/js/textext.plugin.arrow.js'
               ),
            'google-diff-match-patch/diff_match_patch.js',
            'jquery.are-you-sure/jquery.are-you-sure.js',
            output='bundles/js_all.js'
        ),
        filters='rjsmin'
    )
    assets.register(
        'codemirror_js_all',
        Bundle('codemirror/lib/codemirror.js',
               'codemirror/mode/rst/rst.js',
               'codemirror/mode/xml/xml.js',
               'codemirror/addon/mode/overlay.js',
               'codemirror/addon/dialog/dialog.js',
               'codemirror/addon/search/searchcursor.js',
               'codemirror/addon/search/search.js',
               'codemirror/addon/scroll/annotatescrollbar.js',
               'codemirror/addon/search/matchesonscrollbar.js',
               'codemirror/addon/search/jump-to-line.js',
               'codemirror/addon/merge/merge.js',
           ),
        'codemirror-addon.js',
        output='bundles/codemirror_all.js',
        filters='rjsmin'
    )
    assets.register(
        'css_all',
        Bundle(
            'style.css',
            'uikit/dist/css/uikit.min.css',
            Bundle('jquery-textext/src/css/textext.core.css',
                   'jquery-textext/src/css/textext.plugin.tags.css',
                   'jquery-textext/src/css/textext.plugin.autocomplete.css',
                   'jquery-textext/src/css/textext.plugin.focus.css',
                   'jquery-textext/src/css/textext.plugin.prompt.css',
                   'jquery-textext/src/css/textext.plugin.clear.css',
                   'jquery-textext/src/css/textext.plugin.arrow.css'
               ),
            'uikit-style.css',
            output='bundles/css_all.css'
        ),
        filters='cssmin'
    )
    assets.register(
        'codemirror_css_all',
        Bundle('codemirror/lib/codemirror.css',
               'codemirror/addon/merge/merge.css',
               'codemirror/addon/dialog/dialog.css',
               'codemirror/addon/search/matchesonscrollbar.css'),
        'codemirror-addon.css',
        output='bundles/codemirror_all.css',
        filters='cssmin'
    )

    import application.views
    import application.views.users
    import application.views.projects
    import application.views.threads
    import application.views.branches
    app.register_blueprint(application.views.users.users)
    app.register_blueprint(application.views.projects.projects)
    app.register_blueprint(application.views.threads.threads)
    app.register_blueprint(application.views.branches.branches)
    # Read extra config settings from extra arguments
    app.config.update(extra_config_settings)
    # Register template filters
    for (i, j) in [('force_unicode', utils.force_unicode),
          ('extract_author_name', utils.extract_author_name),
          ('formattimestamp', utils.formattimestamp),
          ('timesince', utils.timesince),
          ('rst2html', utils.rst2html)]:
        app.jinja_env.filters[i] = j
    # Set languange
    app.config['LANGUAGE'] = 'pt_BR'
    if app.testing or app.config['TESTING']:
        # Disable CSRF checks while testing
        app.config['WTF_CSRF_ENABLED'] = False
        app.config['LANGUAGE'] = 'en_US'
        app.config['BOOKCLOUD_URL_PREFIX'] = ''

    #app.register_blueprint(application.views.temp,
    #                       url_prefix=app.config['BOOKCLOUD_URL_PREFIX'])

    # Setup Flask-Mail
    mail.init_app(app)
    # Setup babel
    babel.init_app(app)
    # Setup Flask-User
    db_adapter = SQLAlchemyAdapter(db, User)        # Register the User model
    user_manager = UserManager(db_adapter, app)     # Initialize Flask-User

    return app

application/branches/__init__.py
from model import *
from forms import *
from tasks import *

application/projects/__init__.py
from model import *
from forms import *

application/tasks/__init__.py
from projects import *

application/users/__init__.py
from model import *
from forms import *

application/views/tasks.py
import re

from application import app, limiter, ext
from flask import jsonify

from application.views import internal_server_error

from pygtail import Pygtail

from celery.result import AsyncResult

#from werkzeug.utils import secure_filename

@limiter.exempt
@app.route('/tasks/<path:task_id>')
def tasks(task_id):
    task_id = re.sub('/', '', task_id)
    task = AsyncResult(task_id)

    if (task.state == 'PENDING'):
        return jsonify({ 'state': task.state })

    if (task.state == 'PROGRESS'):
        return jsonify({ 'state': task.state,
                         'status': task.info.get('status', '') })

    if (task.state == 'FAILURE'):
        internal_server_error(task.result)
        return jsonify({ 'state': task.state,
                         'result': task.result.message,
                         'traceback': task.traceback })

    if (task.state == 'SUCCESS'):
        return jsonify({ 'state': task.state })

    return jsonify({ 'state': task.state })

application/views/threads.py
import urllib
import json
from sets import Set
from datetime import datetime
from os.path import join

from flask import (
    Blueprint, request, render_template,
    url_for, flash, redirect, g, abort
)
from flask_user import login_required, current_user
from flask_babel import gettext as _
from flask_mail import Message
from sqlalchemy import or_, not_, desc

import application
from application import db, app, limiter, mail
from application.users import User
from application.utils import rst2html
from application.threads import (
    Thread, Comment, File_Tag, Free_Tag, Named_Tag, CommentSearchForm,
    ThreadForm, NewThreadForm, CommentForm, ThreadQueryForm, user_read_thread
)
from application.projects import Project

threads = Blueprint('threads', __name__)

@threads.url_value_preprocessor
def get_branch_object(endpoint, values):
    g.project = Project.get_by_name(values.get('project'))
    values['project'] = g.project

@threads.before_request
def threads_before_request():
    application.views.projects.projects_before_request()

@threads.context_processor
def threads_context_processor():
    return { 'project': g.project,
             'menu': g.menu }

@threads.route('/<project>/new_thread', methods = ['GET', 'POST'])
@login_required
def newthread(project):
    inputs = {'user_tags': '', 'file_tags': '',
              'custom_tags': '', 'free_tags': ''}
    for t in inputs:
        inputs[t] = request.args.get(t) if request.args.get(t) else ''
    # In the next line we are deleting some inputs if they
    # were inserted but not validated in a previous new_thread view
    form = NewThreadForm(request.form,
                         user_tags=inputs['user_tags'].split(","),
                         file_tags=inputs['file_tags'].split(","),
                         custom_tags=inputs['custom_tags'].split(","),
                         free_tags=inputs['free_tags'])
    form.user_tags.widget.choices = json.dumps(
        [u.username for u in User.query.all()])
    form.file_tags.widget.choices = project.get_labels()
    form.custom_tags.widget.choices = json.dumps(
        [t.name for t in Named_Tag.query.filter_by(project=project).all()])
    if request.method == 'POST' and form.validate():
        # create thread
        new_thread = Thread(form.title.data,
                            current_user.id,
                            project.id,
                            form.flag.data,
                            datetime.utcnow())
        # add tags
        new_thread.user_tags = [User.get_by_name(n)
                                for n in form.user_tags.data]
        new_thread.file_tags = [File_Tag(new_thread.id, n)
                                for n in form.file_tags.data]
        new_thread.custom_tags = list(
            Named_Tag.query.filter(Named_Tag.project==project,
                                   Named_Tag.name.in_(form.custom_tags.data))
                           .all())
        new_thread.free_tags = [Free_Tag(new_thread.id, n)
                                for n in form.free_tags.data]
        # add first comment
        new_comment = Comment('000000:',
                              new_thread.id,
                              current_user.id,
                              form.firstcomment.data,
                              datetime.utcnow())
        new_thread.comments = [new_comment]
        db.session.add(new_thread)
        db.session.commit()
        # send emails
        recipients = Set(form.user_tags.data)
        for tags in new_thread.custom_tags:
            recipients = recipients | Set([u.username for u in
                                           tags.subscribed_users])
        # Passing the recipients in the email is just temporary
        # for debugging
        message = render_template('threads/email.html', comment=new_comment,
                                  recipients=recipients)
        #######################################################
        if app.config['TESTING']:
            print('Email should be sent to: ' + str(recipients))
            print(message)
        else:
            with mail.connect() as conn:
                for user in recipients:
                    user_obj = User.get_by_name(user)
                    subject = _('Thread: ') + new_thread.title
                    msg = Message(recipients=[user_obj.email],
                                  subject=subject,
                                  html=message)
                    conn.send(msg)
                app.logger.info('Sending emails to {} users'.format(
                    len(recipients)))
                flash(_('Emails sent to user(s) {}')
                      .format(str(recipients)))
        flash(_('New thread successfully created'), 'info')
        if 'return_url' in request.args:
            redirect(urllib.unquote(request.args['return_url']))
        else:
            return redirect(url_for('threads.query_thread',
                                    project=project.name,
                                    thread_id=new_thread.id))
    return render_template('threads/newthread.html', form=form)

@threads.route('/<project>/edit_thread/<thread_id>', methods = ['GET', 'POST'])
@login_required
def editthread(project, thread_id):
    thread = Thread.get_by_id(thread_id)
    if (current_user != thread.owner):
        flash(_('You are not allowed to edit this thread'), 'error')
        return redirect(url_for('branches.view', project=project.name,
                                branch='master', filename='index'))
    form = ThreadForm(
        request.form,
        title=thread.title,
        flag=thread.flag,
        user_tags=[t.username for t in thread.user_tags],
        file_tags=[t.filename for t in thread.file_tags],
        custom_tags=[t.name for t in thread.custom_tags],
        free_tags=[t.name for t in thread.free_tags])
    form.user_tags.widget.choices = json.dumps(
        [u.username for u in User.query.all()])
    form.file_tags.widget.choices = project.get_labels()
    form.custom_tags.widget.choices = json.dumps(
        [t.name for t
         in Named_Tag.query.filter_by(project=project).all()])
    master_path = join('repos', project.name, 'master', 'source')
    if request.method == 'POST' and form.validate():
        thread.title = form.title.data
        thread.flag = form.flag.data
        # add tags
        thread.user_tags = [User.get_by_name(n)
                            for n in form.user_tags.data]
        thread.file_tags = [File_Tag(thread.id, n)
                            for n in form.file_tags.data]
        thread.custom_tags = list(
            Named_Tag.query.filter(Named_Tag.project==project,
                                   Named_Tag.name.in_(form.custom_tags.data))
                           .all())
        thread.free_tags = [Free_Tag(thread.id, n)
                            for n in form.free_tags.data]
        db.session.commit()
        app.logger.info('Updating thread {}'.format(thread.id))
        flash(_('Thread successfully modified'), 'info')
        if 'return_url' in request.args:
            return redirect(urllib.unquote(request.args['return_url']))
        else:
            return redirect(url_for('branches.view', project=project.name,
                                    branch='master', filename='index'))
    return render_template('threads/editthread.html', form=form)

@threads.route('/<project>/delete_thread/<int:thread_id>')
@login_required
def deletethread(project, thread_id):
    thread = Thread.get_by_id(thread_id)
    if Comment.query.filter_by(thread_id=thread_id).first():
        flash(_('Thread is not empty'), 'error')
    else:
        thread = Thread.query.filter_by(id=thread_id).first()
        if not current_user.is_authenticated:
            flash(_('You must be logged in to delete a thread'), 'error')
        else:
            if (current_user != thread.owner
                and current_user != project.get_master().owner):
                flash(_('You are not allowed to delete this thread'), 'error')
            else:
                thread.delete()
                db.session.commit()
                app.logger.info('Deleting thread {}'.format(thread.id))
                flash(_('Thread successfully deleted'), 'info')
    if 'return_url' in request.args:
        return redirect(urllib.unquote(request.args['return_url']))
    else:
        return redirect(url_for('branches.view', project=project.name,
                                branch='master', filename='index'))

@threads.route('/<project>/new_comment/<thread_id>', methods = ['GET', 'POST'])
@threads.route('/<project>/new_comment/<thread_id>/<parent_lineage>',
               methods = ['GET', 'POST'])
@login_required
def newcomment(project, thread_id, parent_lineage=''):
    form = CommentForm(request.form)
    if (parent_lineage != ''):
        try:
           (Comment.query.filter(Comment.thread_id==thread_id)
            .filter(Comment.lineage==parent_lineage).one())
        except:
            abort(404)
    if request.method == 'POST' and form.validate():
        thread = Thread.get_by_id(thread_id)
        thread.user_read_thread = [current_user]
        siblings_pattern = parent_lineage + '%'
        decend_comments = (Comment.query
                           .filter(Comment.thread_id==thread_id)
                           .filter(Comment.lineage.like(siblings_pattern)))
        number_siblings = decend_comments.count()
        new_comment_lineage = (parent_lineage
                               + format(number_siblings, '06X') + ':')
        new_comment = Comment(new_comment_lineage,
                              thread_id,
                              current_user.id,
                              form.comment.data,
                              datetime.utcnow())
        db.session.add(new_comment)
        db.session.commit()
        # send emails
        recipients = Set([tag.username for tag in thread.user_tags])

application/templates/threads/_display_threads.html
{% macro display_threads(threads) %}

<!-- Threads -->

<script>
  function likeFunction(url, is_like, comment_id) {
  $.post(url, {'is_like': is_like}, function(data, status) {
    var data_obj = JSON.parse(data);
    if (data_obj['status'] == 'success') {
      UIkit.notification(data_obj['message'],
        {status: 'success', pos: 'bottom-center'});
    } else {
      UIkit.notification(data_obj['message'],
        {status: 'danger', pos: 'bottom-center'});
    }
    $('#number-of-likes-' + comment_id)
      .text(data_obj['number_of_likes']);
  })
  }

  function showComments(url, is_read, thread_id) {
  $.post(url, {'is_read': is_read}, function(data, status) {
    var data_obj = JSON.parse(data);
    if (data_obj['status'] == 'success') {
      UIkit.notification(data_obj['message'],
        {status: 'success', pos: 'bottom-center'});
    } else {
      UIkit.notification(data_obj['message'],
        {status: 'danger', pos: 'bottom-center'});
    }
    $('#unread-label-' + thread_id).remove();
  })
  }
</script>

<!-- Scroll Up -->
<a href="" class="uk-align-right" uk-scroll>
  <span uk-icon="icon: chevron-up; ratio: 2"
        title="{{ _('Go to top') }}" uk-tooltip></span>
</a>
<hr class="uk-divider-icon">
<a name="discussion"></a>
<div class="uk-container uk-container-center">
  {% for t in threads %}
    <article class="uk-article uk-margin-top">
      <header class="uk-comment-header uk-position-relative
                     uk-background-muted">
        <hr>
        <div class="uk-grid-small uk-flex-middle
                    uk-margin-left" uk-grid>
          <div class="uk-width-auto">
            <canvas width="40" height="40"
                    data-jdenticon-hash="{{ hash(t.author.username) }}"
                    style="vertical-align: baseline;">
            </canvas>
          </div>
          <div class="uk-width-expand">
            <p style="margin: 0 0 0 0;">
              {{ t.author.username }} ({{ t.flag }}) -
              {{ t.posted_at }} - ({{ t.comments.count() }}
              {{ _('comments') }}):
            </p>
            <h4 style="margin-top: 0;"> {{ t.title }} </h4>
          </div>
          <div class="uk-position-top-right uk-position-small">
            {% if (current_user == t.author
                   or current_user.username == project.owner) %}
              <a href="{{ url_for('threads.editthread',
                       project=t.project.name, thread_id=t.id,
                       return_url=url_encode(url_for('threads.query_thread', project=project.name, thread_id=t.id))) }}"
                       class="uk-link-muted" uk-icon="icon: pencil"
                       title="{{ _('Edit thread') }}" uk-tooltip>
              </a>
              {% if t.comments.count() == 0 %}
                <a href="{{ url_for('threads.deletethread',
                         project=t.project.name, thread_id=t.id,
                         return_url=url_encode(url_for('threads.query_thread', project=project.name, thread_id=t.id))) }}"
                         onclick="return confirm('Are you sure?')"
                         class="uk-link-muted" uk-icon="icon: trash"
                         title="{{ _('Delete thread') }}" uk-tooltip>
                </a>
              {% endif %}
            {% endif %}
          </div>
        </div>
        <div class="uk-grid-small uk-flex-middle
                    uk-margin-left" uk-grid>
          <div class="uk-width-auto">
            {% if t.user_tags %}
              <span uk-icon="icon: users"
                    title="{{ _('Users') }}" uk-tooltip></span>
              {% for tag in t.user_tags %}
                &nbsp;
                <span class="uk-label">{{ tag.username }}</span>
              {% endfor %} &emsp;
            {% endif %}
            {% if t.file_tags %}
              <span uk-icon="icon: link"
                    title="{{ _('Link to text') }}" uk-tooltip></span>
              {% for file in t.file_tags %}
                &nbsp;
                <a class="uk-label"
                   href="{{ url_for('branches.view',
                                    project=project.name,
                                    branch='master',
                                    filename=label_file_dict[file.filename]) }}#{{ file.filename }}">
                  {{ file.filename }}
                </a>
              {% endfor %} &emsp;
            {% endif %}
            {% if t.custom_tags %}
              <span uk-icon="icon: tag"
                    title="{{ _('Tags') }}" uk-tooltip></span>
              {% for custom in t.custom_tags %}
                &nbsp;
              <span class="uk-label">{{ custom.name }}</span>
              {% endfor %} &emsp;
            {% endif %}
            {% if t.free_tags.count() %}
              <span uk-icon="icon: hashtag"
                    title="{{ _('Hashtags') }}" uk-tooltip></span>
              {% for free in t.free_tags.all() %}
                &nbsp;
                <span class="uk-label">{{ free.name }}</span>
              {% endfor %}
            {% endif %}
          </div>
        </div>
        <hr>
      </header>
      {% if current_user.is_authenticated %}
        {% if not current_user in t.user_read_thread %}
          <a class="uk-link-muted"
             uk-toggle="target: #thread-{{ t.id }}" type="button"
             onclick="showComments('{{ url_for('threads.mark_read',
                                   project=project.name, thread_id=t.id) }}',
                                   true, {{ t.id }})">
            <span class="uk-margin-left" uk-icon="icon: commenting"></span>
            {{ _('Show/hide comments') }}
          </a>
          <span id="unread-label-{{ t.id }}"
                class="uk-label uk-label-danger">Unread</span>
        {% else %}
          <a class="uk-link-muted uk-margin-left"
             uk-toggle="target: #thread-{{ t.id }}" type="button"
            <span class="uk-margin-left" uk-icon="icon: commenting"></span>
            {{ _('Show/hide comments') }}
          </a>
          <a class="uk-link-muted"
             onclick="showComments('{{ url_for('threads.mark_read',
                                   project=project.name, thread_id=t.id) }}',
                                   false, {{ t.id }})"
             uk-toggle>
            <span class="uk-margin-left" uk-icon="icon: mail"></span>
            {{ _('Mark unread') }}
          </a>
        {% endif %}
      {% else %}
          <a class="uk-link-muted uk-margin-left"
             uk-toggle="target: #thread-{{ t.id }}" type="button"
            <span class="uk-margin-left" uk-icon="icon: commenting"></span>
            {{ _('Show/hide comments') }}
          </a>
      {% endif %}
      <ul class="uk-comment-list" id="thread-{{ t.id }}"
          aria-hidden="true" hidden="hidden">
        {% for c in t.get_comments(100) %}
          <li class="uk-margin-remove">
          <article class="uk-comment" style="margin-left:
                                             {{ c.get_indent() }}px;">
            <header class="uk-comment-header uk-position-relative">
              <div class="uk-grid-medium uk-flex-middle" uk-grid>
                <div class="uk-width-auto">
                  <canvas width="30" height="30"
                          data-jdenticon-hash="{{ hash(c.author.username) }}">
                  </canvas>
                </div>
                <div class="uk-width-expand">
                  <a class="uk-link-reset" href="#">{{ c.author.username }}</a>
                  &nbsp;
                  <span class="uk-comment-meta
                               uk-margin-remove-top uk-text-small">
                    {{ c.posted_at }}
                  </span>
                </div>
              </div>
              <div class="uk-position-top-right uk-position-small
                          uk-hidden-hover">
                <span uk-icon="icon: heart"></span>
                <span id="number-of-likes-{{ c.id }}"
                      class="uk-badge">{{ c.likes.count() }}</span>
                {% if (current_user.is_authenticated
                   and current_user != c.author) %}
                  {% if not current_user in c.likes %}
                  <a uk-icon="icon: chevron-up"
                     title="Like" uk-tooltip
                     onclick="likeFunction('{{ url_for('threads.like_comment',
                              project=project.name, comment_id=c.id) }}',
                              true, {{ c.id }})" uk-toggle>
                  </a>
                  {% else %}
                  <a uk-icon="icon: chevron-down"
                     title="Like" uk-tooltip
                     onclick="likeFunction('{{ url_for('threads.like_comment',
                              project=project.name, comment_id=c.id) }}',
                              false, {{ c.id }})" uk-toggle>
                  </a>
                  {% endif %}
                {% endif %}
                &nbsp; &nbsp; &nbsp;
                <a href="{{ url_for('threads.newcomment',
                   project=t.project.name,
                   thread_id = t.id, parent_lineage=c.lineage,
                         return_url=url_encode(url_for('threads.query_thread', project=project.name, thread_id=t.id))) }}"
                   class="uk-link-muted" uk-icon="icon: reply"
                   title="{{ _('Reply') }}" uk-tooltip></a>
                {% if current_user == c.author %}
                  <a href="{{ url_for('threads.editcomment',
                     project=t.project.name, comment_id=c.id,
                           return_url=url_encode(url_for('threads.query_thread', project=project.name, thread_id=t.id))) }}"
                     class="uk-link-muted" uk-icon="icon: pencil"
                     title="{{ _('Edit comment') }}" uk-tooltip></a>
                {% endif %}
                {% if not c.has_replies()
                  and (current_user == c.author
                  or current_user.username == project.owner) %}
                  <a href="{{ url_for('threads.deletecomment',
                           project=t.project.name,
                           comment_id=c.id,
                           return_url=url_encode(url_for('threads.query_thread', project=project.name, thread_id=t.id))) }}"
                           onclick="return confirm('Are you sure?')"
                     class="uk-link-muted" uk-icon="icon: trash"
                     title="{{ _('Delete comment') }}" uk-tooltip></a>
                {% endif %}
              </div>
            </header>
            <div class="uk-comment-body">
              {{ c.content | rst2html | safe }}
            </div>
            <hr>
          </article>
          </li>
        {% endfor %}
      </ul>
      <a href="{{ url_for('threads.newcomment',
                  project=t.project.name, thread_id = t.id,
                  return_url=url_encode(url_encode(url_for('threads.query_thread', project=project.name, thread_id=t.id)))) }}"
         class="uk-link-muted uk-margin-medium-left">
        <span uk-icon="icon: reply"></span>
        New comment
      </a>
    </article>
  {% endfor %}
</div>
{% endmacro %}

application/templates/threads/query_threads.html
{% extends "base_template.html" %}

{% from "_formhelpers.html" import render_field %}

{% from "threads/_display_threads.html" import display_threads with context %}

{% block title %}{{ _('List of comments') }}{% endblock%}

{% macro contents() %}
  <div class="uk-margin-large-left uk-card uk-card-default uk-card-body">
    <legend class="uk-legend">
      {{ _('Threads') }}
      <span class="uk-badge">{{ len(threads.all()) }}</span>
    </legend>
    <a href="{{ url_for('threads.newthread',
                        project=project.name) }}"
       class="uk-button uk-button-default uk-margin"
       type="button">New thread</a>
    <button id="button-show-form"
            class="uk-button uk-button-default uk-margin"
            uk-toggle="target: #toggle-form" type="button">Search</button>
    <form method="GET" id="toggle-form"
          aria-hidden="true" hidden="hidden">
      <fieldset class="uk-fieldset">
        <div class="uk-margin">
          {{ render_field(form.search, style="width: 500px;") }}
        </div>
        <div class="uk-margin">
          {{ render_field(form.unread) }}
        </div>
        <div class="uk-margin">
          {{ render_field(form.user_tags, style="width: 500px;") }}
        </div>
        <div class="uk-margin">
          {{ render_field(form.file_tags, style="width: 500px;") }}
        </div>
        <div class="uk-margin">
          {{ render_field(form.custom_tags, style="width: 500px;") }}
        </div>
        <div class="uk-margin">
          <button class="uk-button uk-button-default">Submit</button>
        </div>
    </form>
  </div>

  {% if threads %}
    {{ display_threads(threads)  }}
  {% endif %}
{% endmacro %}